#!/bin/bash

echo 'Giving camera 2 seconds to start up.'
sleep 2

for i in {1..10}
do
#while true; do
	echo Attempt $i ...

	# Run the grabber script
	timeout 5 ./grabber $1
	out=$?

	# Check the output
	if [ $out -eq 124 ]; then
		echo 'TIMED OUT (after 5 seconds)! Sleeping 3 seconds.'
		sleep 3
	elif [ $out -eq 19 ]; then
		echo 'NO SUCH DEVICE! Sleeping 3 seconds.'
		sleep 3
	elif [ $out -eq 0 ]; then
		echo 'GOT IT!'
		break
	else
		echo 'NO IDEA! Sleeping 3 seconds.'
 		sleep 3
	fi

	i=$[$i+1]]
done
